In [1]:
import copy, math
import numpy as np
import matplotlib.pyplot as plt

In [84]:
X_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
y_train = np.array([460, 232, 178])

In [3]:
print(f"X Shape: {X_train.shape}, X Type:{type(X_train)})")
print(X_train)
print(f"y Shape: {y_train.shape}, y Type:{type(y_train)})")
print(y_train)
#这里我有一个奇怪的误会，我一直以为y.shape:(3,)和x（3，4）
#这里的x值得是一个二位矩阵三个样本和四个特征
#y指的是一个一维数组三个样本，这里的,是为了区分数组和标量并不意味着别的什么

X Shape: (3, 4), X Type:<class 'numpy.ndarray'>)
[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
y Shape: (3,), y Type:<class 'numpy.ndarray'>)
[460 232 178]


In [83]:
b_init = 785.1811367994083
w_init = np.array([ 0.39133535, 18.75376741, -53.36032453, -26.42131618])
print(f"w_init shape: {w_init.shape}, b_init type: {type(b_init)}")

w_init shape: (4,), b_init type: <class 'float'>


# 写这个函数不是为了让你照抄重要的是理解最好你手搓一个之后再核对

In [5]:
#手搓time-还挺有意思的
def pritict_by_loop(x,w,b):
    #初始化
    p=0
    n=x.train.shape
    for i in range(n):
        p[i]=w[i]*x[i]
        p=p+p[i]
    p=p+b
    

In [6]:
#对答案时间到
def predict_single_loop(x,w,b):
    n=x.shape[0] #0对一个二维数组来说是样本的数目
    p=0
    for i in range(n):
        p_i=w[i]*x[i] #这里好像有一点问题，就是p他本身不是数组他不能向你那样调用
        p=p+p_i
    p=p+b
    return p
    

In [11]:
#继续手搓时间——随便计算一下试验一下
x_test=X_train[0] #这里你对numpy的切片操作还是很不熟悉，但是没想到你这样也可以，正好稍微复习一下
print(f"x_test= {x_test}")
f_wb=predict_single_loop(x_test,w_init,b_init)
print(f"prediction:{f_wb}")



x_test= [2104    5    1   45]
prediction:459.9999976194083


问题 1：创建数组
使用 np.array 创建一个一维数组，内容为 [1, 2, 3, 4, 5]。
使用 np.arange 创建一个从 0 到 9（包含 0 和 9）的数组。
使用 np.linspace 创建一个从 0 到 1 的数组，包含 5 个等间距的值。
使用 np.zeros 创建一个形状为 (3, 4) 的全零矩阵。
使用 np.ones 创建一个形状为 (2, 2) 的全一矩阵。
使用 np.eye 创建一个 3x3 的单位矩阵（主对角线为 1，其余为 0）。
使用 np.random.rand 创建一个形状为 (2, 3) 的随机数矩阵（值在 [0, 1) 区间内）。


问题 2：取值操作
假设我们有一个二维数组：



arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
完成以下操作：

取出第一行的所有元素。
取出最后一列的所有元素。
取出第二行第二列的单个元素。
取出子数组 [[5, 6], [8, 9]]。
使用布尔索引取出所有大于 5 的元素。


问题 3：修改数组
将 arr 中所有大于 5 的元素替换为 0。
将 arr 的第一行替换为 [10, 11, 12]。
在 arr 的末尾添加一行 [13, 14, 15]。



问题 4：其他操作
计算 arr 的转置（行列互换）。
计算 arr 的所有元素的平均值。
找到 arr 中的最大值及其索引位置。
按列计算 arr 的累加和（即每一列的累加结果）。

In [32]:
#稍微复习一下numpy中的操作
##回答ai提出来的问题
###创建数组
a=np.array([1,2,3,4,5])
print(f"a={a}")
b=np.arange(10)
print(f"b={b}")
c=np.linspace(0,1,5) #这个也很陌生
print(f"c={c}")
d=np.zeros([3,4])
print(f"d={d}")
e=np.ones([2,2])
print(f"e={e}")
#f=np.eye([3,3],) #不会我没试过这个完全
#print(f"f={f}")
#f=np.random.rand([2,2]) #还是不会
#print(f"f={f}")

### 取值操作
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a=arr[0]
print(f"a={a}")
#b=arr[,2] #我不太会取最后一列的元素
#b
c=arr[1,1]
print(f"c={c}")
#d=arr[] #不会
#e=arr #不会


### 修改数组
#完全不会
###其他操作
#也完全不会

SyntaxError: invalid syntax (133760818.py, line 23)

In [34]:
#来吧你最喜欢干的事情抄答案，妈的做的一身冷汗
# 1.创建数组
d=np.zeros([3,4]) #考考你这里（3,4）和【3,4】有什么区别？我的理解是前者是元组后者是列表，前者没办法改变后者可以改变，所以为什么我一定要用元祖呢？列表不行吗？
#好吧就是规定是一个元组同时形状是不可更改的
f = np.eye(3)
print(f"f={f}")
g = np.random.rand(2, 3)
print(f"g={g}")

# 2. 取值
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = arr[:, -1] #我之前理解错了，实际上：值得是全选，才是分割
print(f"b={b}")
d=arr[1:,1:]#第二行以后的和第二列以后的
e=arr[arr>5]
g=arr[arr>5]
h=arr[0]=[10,11,12]
i=np.vstack((arr,[13,14,15]))
t_arr=arr.T
mean=arr.mean()
max=arr.max()


f=[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
g=[[0.79438781 0.1608789  0.39352998]
 [0.35685607 0.6314657  0.36833959]]
b=[3 6 9]


In [68]:
#ok 我又觉得我行了，再来试一下
## 创建数组
x_learn=np.array([[10,20,30],[40,50,60]])
print(f"x_learn={x_learn}")
a=np.arange(1,13)
a=a.reshape(3,4) #原来直接这样就可以了
print(f"reshape{a}")
b=np.ones([2,3])
b=b*5
## 取值操作
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
a=arr[1,]
b=arr[:,0]
c=arr[1,1:]
d=arr[arr<5]
#修改数组
# 改是改了能不能找一个中间过渡态啊
brr=arr
arr[arr<5]=0
arr[2]=[10,11,12]
np.vstack((arr,[13,14,15]))
t_arr=arr.T
sum=arr.sum()
min=arr.min()
sum_0=arr.sum(1) #这里好像是1是按照行算的2是按照列算的
#哈哈哈我已经是数组高手了！至少基础操作会了

x_learn=[[10 20 30]
 [40 50 60]]
reshape[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [64]:
sum

44

In [65]:
sum_0

array([ 0, 11, 33])

In [66]:
arr

array([[ 0,  0,  0],
       [ 0,  5,  6],
       [10, 11, 12]])

In [69]:
#继续回到我的主线尝试一下dot product
def predict(x,w,b):
    p=np.dot(x,w)+b #感觉这个确实没办法手搓啊我都没见过np.dot是怎么使用的
    return p #哎但是我是天才，笑

In [71]:
x_vec=X_train[0,:]
f_wb=predict(x_vec,w_init,b_init)
print(f"f_wb={f_wb}") #天菜

f_wb=459.9999976194083


In [95]:
# compute cost with multiple variables
def cost_function(X,y,w,b):
    m=X_train.shape[0]
    cost=0
    for i in range(m):
        f_wb_i=np.dot(X[i],w)+b
        cost=cost+(f_wb_i-y)**2
    cost=cost/(2*m)
    return cost     #easy啊 我越来越熟练了

In [74]:
cost=compute_cost(X_train,y_train,w_init,b_init)
print(f"cost={cost}") 
#哦哦哦好神奇原来是三个cost 虽然和她的lab里面不一样，但我思考了一下我应该是对的，就是对应三个w_init,生成了三个cost 根本还没有最佳呢看个锤子w

cost=[21918.00021892  9149.99983727 13739.99974687]


In [96]:
def gradient_function(X,y,w,b):
    m,n=X.shape
    dj_dw=np.zeros((n,))
    dj_db=0
    for i in range(m):
        err=(np.dot(X[i],w)+b)-y[i]
        for j in range(n):
            dj_dw[j]=dj_dw[j]+err*X[i,j] #这是哪个东西求导后的结果
        dj_db=dj_db+err
    dj_dw=dj_dw/m 
    dj_db=dj_db/n 

    return dj_db,dj_dw #抄的哈 这个有点难了

In [89]:
tmp_dj_db, tmp_dj_dw = compute_gradient(X_train, y_train, w_init, b_init)
print(f'dj_db at initial w,b: {tmp_dj_db}')
print(f'dj_dw at initial w,b: \n {tmp_dj_dw}')

dj_db at initial w,b: -1.2554438626466435e-06
dj_dw at initial w,b: 
 [-2.72623577e-03 -6.27197263e-06 -2.21745578e-06 -6.92403391e-05]


In [99]:
#开始进行最后一步多变量的梯度下降
def gradient_descent(X,y,w_in,b_in,cost_function,gradient_function,alpha,num_iters):
    J_history=[]
    w=copy.deepcopy(w_in) #不直接在上面就叫w的原因是为了防止命名错误
    b=b_in

    for i in range(num_iters): #唉参数多了真得写注释，这里是迭代次数
        dj_db,dj_dw=gradient_function(X,y,w,b)
        w=w-alpha*dj_dw
        b=b-alpha*dj_db

        if i <10000:
            J_history.append(cost_function(X,y,w,b))
        if i% math.ceil(num_iters/10)==0:
            print(f"Iteration {i}:Cost {J_history[-1]} ")
    return w,b,J_history

In [100]:
# initialize parameters
initial_w = np.zeros_like(w_init)
initial_b = 0.
# some gradient descent settings
iterations = 1000
alpha = 5.0e-7
# run gradient descent 
w_final, b_final, J_hist = gradient_descent(X_train, y_train, initial_w, initial_b,
                                                    compute_cost, compute_gradient, 
                                                    alpha, iterations)
print(f"b,w found by gradient descent: {b_final:0.2f},{w_final} ")
m,_ = X_train.shape
for i in range(m):
    print(f"prediction: {np.dot(X_train[i], w_final) + b_final:0.2f}, target value: {y_train[i]}")

Iteration 0:Cost [13473.48080976 14829.77758876 22765.00577326] 
Iteration 100:Cost [19009.60689546  7337.65021208 12187.23941865] 
Iteration 200:Cost [19020.04824289  7342.91980587 12191.28412341] 
Iteration 300:Cost [19030.44793224  7348.1706845  12195.31554688] 
Iteration 400:Cost [19040.80610703  7353.40288973 12199.33370669] 
Iteration 500:Cost [19051.12291051  7358.61646349 12203.33862078] 
Iteration 600:Cost [19061.39848564  7363.81144789 12207.33030738] 
Iteration 700:Cost [19071.63297511  7368.98788521 12211.30878497] 
Iteration 800:Cost [19081.82652134  7374.14581788 12215.27407232] 
Iteration 900:Cost [19091.97926647  7379.28528852 12219.22618848] 
b,w found by gradient descent: -0.00,[ 0.20396536  0.00374919 -0.01124872 -0.06586182] 
prediction: 426.19, target value: 460
prediction: 286.17, target value: 232
prediction: 171.47, target value: 178
